version: "3.5"

services:

  client-app-dev:
    container_name: client-app-dev
    image: marica/web-app-client-dev
    build:
      context: .
      dockerfile: client.Dockerfile
      target: development
    ports:
      - "4001:4001"
    volumes:
      - ./:/app
    env_file:
      - docker.dev.env
    networks:
      - cookbook-dev
    depends_on:
      - server-app-dev

  server-app-dev:
    container_name: server-app-dev
    image: marica/web-app-server-dev
    build:
      context: .
      dockerfile: server.Dockerfile
      target: development
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/cookbook-server/node_modules/bcrypt
    environment:
      - DATABASE_URI=mongodb://db-container/cookbook
    env_file:
     - docker.dev.env
    networks:
      - cookbook-dev
    links:
      - mongo

  mongo:
    container_name: db-container
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27018:27017"
    networks:
      - cookbook-dev

networks:
  cookbook-dev:
    driver: bridge
    name: asw-cookbook-dev